# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Get Hangar
email: get@thehangar.cr
description: > # this means to ignore newlines until "baseurl:"
  Hangar look and feel to your static content websites.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gethangar.cr" # the base hostname & protocol for your site
twitter_username: hangar_cr
github_username:  hangarcr

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Where things are
encoding:         UTF-8
source:          	./docs
destination:      ./_site
sass:
  style: :compressed
